//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductV2_Renewal
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<decimal> CheSun { get; set; }
        public Nullable<decimal> SanZhe { get; set; }
        public Nullable<decimal> DaoQiang { get; set; }
        public Nullable<decimal> SiJi { get; set; }
        public Nullable<decimal> ChengKe { get; set; }
        public Nullable<int> BoLi { get; set; }
        public Nullable<decimal> HuaHen { get; set; }
        public Nullable<decimal> BuJiMianCheSun { get; set; }
        public Nullable<decimal> BuJiMianSanZhe { get; set; }
        public Nullable<decimal> BuJiMianDaoQiang { get; set; }
        public Nullable<decimal> BuJiMianRenYuan { get; set; }
        public Nullable<decimal> BuJiMianFuJia { get; set; }
        public Nullable<decimal> SheShui { get; set; }
        public Nullable<decimal> CheDeng { get; set; }
        public Nullable<decimal> ZiRan { get; set; }
        public Nullable<int> ChuXianCiShu { get; set; }
        public Nullable<decimal> WuPeiKuanYouHui { get; set; }
        public Nullable<decimal> ChuXianPeiKuanJin { get; set; }
    }
}
