//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductV2_User
    {
        public int Id { get; set; }
        public string CarUsedType { get; set; }
        public string LicenseNo { get; set; }
        public string LicenseOwner { get; set; }
        public string PostedName { get; set; }
        public string InsuredName { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string IdType { get; set; }
        public string CredentislasNum { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string EngineNo { get; set; }
        public string ModleName { get; set; }
        public string RegisterDate { get; set; }
        public string CarVin { get; set; }
        public string ForceExpireDate { get; set; }
        public string BusinessExpireDate { get; set; }
        public Nullable<int> SeatCount { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> Channel { get; set; }
        public string CustomerKey { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public string Memo { get; set; }
        public Nullable<int> VisitStatus { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> VisitServiceUserId { get; set; }
    }
}
