//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadPack
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserOpenId { get; set; }
        public int Amount { get; set; }
        public string ActivityName { get; set; }
        public string Wishing { get; set; }
        public string Remark { get; set; }
        public string ClientIP { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime SendTime { get; set; }
    }
}
