//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductV2UserItemPolicy
    {
        public int Id { get; set; }
        public string CarUsedType { get; set; }
        public string LicenseNo { get; set; }
        public string LicenseOwner { get; set; }
        public string PostedName { get; set; }
        public string InsuredName { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string IdType { get; set; }
        public string CredentislasNum { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string EngineNo { get; set; }
        public string ModleName { get; set; }
        public string RegisterDate { get; set; }
        public string ForceExpireDate { get; set; }
        public string CarVin { get; set; }
        public string BusinessExpireDate { get; set; }
        public Nullable<int> SeatCount { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> Channel { get; set; }
        public string CustomerKey { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public string Memo { get; set; }
        public Nullable<int> ProductItemId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<decimal> BizRate { get; set; }
        public Nullable<decimal> BizTotal { get; set; }
        public Nullable<decimal> ForceRate { get; set; }
        public Nullable<decimal> ForceTotal { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<int> QuoteStatus { get; set; }
        public string QuoteResult { get; set; }
        public Nullable<decimal> CheSun_BaoE { get; set; }
        public Nullable<decimal> CheSun_BaoFei { get; set; }
        public Nullable<decimal> SanZhe_BaoE { get; set; }
        public Nullable<decimal> SanZhe_BaoFei { get; set; }
        public Nullable<decimal> DaoQiang_BaoE { get; set; }
        public Nullable<decimal> DaoQiang_BaoFei { get; set; }
        public Nullable<decimal> SiJi_BaoE { get; set; }
        public Nullable<decimal> SiJi_BaoFei { get; set; }
        public Nullable<decimal> ChengKe_BaoE { get; set; }
        public Nullable<decimal> ChengKe_BaoFei { get; set; }
        public Nullable<decimal> BoLi_BaoE { get; set; }
        public Nullable<decimal> BoLi_BaoFei { get; set; }
        public Nullable<decimal> HuaHen_BaoE { get; set; }
        public Nullable<decimal> HuaHen_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianCheSun_BaoE { get; set; }
        public Nullable<decimal> BuJiMianCheSun_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianSanZhe_BaoE { get; set; }
        public Nullable<decimal> BuJiMianSanZhe_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianDaoQiang_BaoE { get; set; }
        public Nullable<decimal> BuJiMianDaoQiang_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianRenYuan_BaoE { get; set; }
        public Nullable<decimal> BuJiMianRenYuan_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianFuJia_BaoE { get; set; }
        public Nullable<decimal> BuJiMianFuJia_BaoFei { get; set; }
        public Nullable<decimal> SheShui_BaoE { get; set; }
        public Nullable<decimal> SheShui_BaoFei { get; set; }
        public Nullable<decimal> CheDeng_BaoE { get; set; }
        public Nullable<decimal> CheDeng_BaoFei { get; set; }
        public Nullable<decimal> ZiRan_BaoE { get; set; }
        public Nullable<decimal> ZiRan_BaoFei { get; set; }
        public Nullable<int> BuId { get; set; }
        public Nullable<byte> SubmitStatus { get; set; }
        public string SubmitResult { get; set; }
        public string BizNo { get; set; }
        public string ForceNo { get; set; }
        public Nullable<decimal> BizRate_Channel { get; set; }
        public Nullable<decimal> ForceRate_Channel { get; set; }
        public Nullable<decimal> TaxRate_Channel { get; set; }
        public Nullable<decimal> BizAfterCoupon { get; set; }
        public Nullable<decimal> ForceAfterCoupon { get; set; }
        public Nullable<decimal> TaxAfterCoupon { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalAfterCoupon { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ItemCreateTime { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdCardType { get; set; }
        public string IdCard { get; set; }
        public string IdCardFacePicUrl { get; set; }
        public string IdCardBackPicUrl { get; set; }
        public string OrganizationCode { get; set; }
        public Nullable<System.DateTime> PolicyCreateTime { get; set; }
        public Nullable<int> ItemUserId { get; set; }
        public Nullable<int> PolicyUserId { get; set; }
        public Nullable<int> RenewalId { get; set; }
        public Nullable<int> RenewalUserId { get; set; }
        public Nullable<int> BSource { get; set; }
        public Nullable<decimal> CheSun { get; set; }
        public Nullable<decimal> SanZhe { get; set; }
        public Nullable<decimal> DaoQiang { get; set; }
        public Nullable<decimal> SiJi { get; set; }
        public Nullable<decimal> ChengKe { get; set; }
        public Nullable<int> BoLi { get; set; }
        public Nullable<decimal> HuaHen { get; set; }
        public Nullable<decimal> BuJiMianCheSun { get; set; }
        public Nullable<decimal> BuJiMianSanZhe { get; set; }
        public Nullable<decimal> BuJiMianDaoQiang { get; set; }
        public Nullable<decimal> BuJiMianRenYuan { get; set; }
        public Nullable<decimal> BuJiMianFuJia { get; set; }
        public Nullable<decimal> SheShui { get; set; }
        public Nullable<decimal> CheDeng { get; set; }
        public Nullable<decimal> ZiRan { get; set; }
        public Nullable<int> ChuXianCiShu { get; set; }
        public Nullable<decimal> WuPeiKuanYouHui { get; set; }
        public Nullable<decimal> ChuXianPeiKuanJin { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> BaseCrateTime { get; set; }
        public Nullable<decimal> AmountPayable { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<int> BaseStatus { get; set; }
        public string TradeNo { get; set; }
        public Nullable<int> BaseChannel { get; set; }
        public string BaseUserId { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public string InvoiceTitle { get; set; }
        public int BaseId { get; set; }
    }
}
