//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HONGLI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductUserItem
    {
        public int Id { get; set; }
        public string LicenseNo { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CityCode { get; set; }
        public string EngineNo { get; set; }
        public string MoldName { get; set; }
        public string RegisterDate { get; set; }
        public string CarVin { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> LastYearSource { get; set; }
        public Nullable<int> QuoteStatus { get; set; }
        public string ForceExpireDate { get; set; }
        public string BusinessExpireDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public string Memo { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> BuId { get; set; }
        public Nullable<decimal> BizTotal { get; set; }
        public Nullable<decimal> ForceTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<int> ItemSource { get; set; }
        public Nullable<int> SubmitStatus { get; set; }
        public string SubmitResult { get; set; }
        public Nullable<int> ItemQuoteStatus { get; set; }
        public string QuoteResult { get; set; }
        public string ExpireDate { get; set; }
        public Nullable<decimal> CheSun_BaoE { get; set; }
        public Nullable<decimal> CheSun_BaoFei { get; set; }
        public Nullable<decimal> SanZhe_BaoE { get; set; }
        public Nullable<decimal> SanZhe_BaoFei { get; set; }
        public Nullable<decimal> DaoQiang_BaoE { get; set; }
        public Nullable<decimal> DaoQiang_BaoFei { get; set; }
        public Nullable<decimal> SiJi_BaoE { get; set; }
        public Nullable<decimal> SiJi_BaoFei { get; set; }
        public Nullable<decimal> ChengKe_BaoE { get; set; }
        public Nullable<decimal> ChengKe_BaoFei { get; set; }
        public Nullable<decimal> BoLi_BaoE { get; set; }
        public Nullable<decimal> BoLi_BaoFei { get; set; }
        public Nullable<decimal> HuaHen_BaoE { get; set; }
        public Nullable<decimal> HuaHen_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianCheSun_BaoE { get; set; }
        public Nullable<decimal> BuJiMianCheSun_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianSanZhe_BaoE { get; set; }
        public Nullable<decimal> BuJiMianSanZhe_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianDaoQiang_BaoE { get; set; }
        public Nullable<decimal> BuJiMianDaoQiang_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianRenYuan_BaoE { get; set; }
        public Nullable<decimal> BuJiMianRenYuan_BaoFei { get; set; }
        public Nullable<decimal> BuJiMianFuJia_BaoE { get; set; }
        public Nullable<decimal> BuJiMianFuJia_BaoFei { get; set; }
        public Nullable<decimal> SheShui_BaoE { get; set; }
        public Nullable<decimal> SheShui_BaoFei { get; set; }
        public Nullable<decimal> CheDeng_BaoE { get; set; }
        public Nullable<decimal> CheDeng_BaoFei { get; set; }
        public Nullable<decimal> ZiRan_BaoE { get; set; }
        public Nullable<decimal> ZiRan_BaoFei { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ItemMobile { get; set; }
        public Nullable<decimal> BussinessCouponRate { get; set; }
        public Nullable<decimal> ForceCouponRate { get; set; }
        public Nullable<decimal> TaxCouponRate { get; set; }
        public Nullable<decimal> BussinessAfterCoupon { get; set; }
        public Nullable<decimal> ForceAfterCoupon { get; set; }
        public Nullable<decimal> TaxAfterCoupon { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> OriginalTotal { get; set; }
    }
}
